### ISSUE TITLE
Newer OptiScaler

### ISSUE THREAD

**Issue by sunnybeats** [FakeMichau/fgmod#11]
Hey, is it possible to invlude a newer version of optiscaler?

https://www.nexusmods.com/site/mods/986?tab=description

**Comment by FakeMichau** [comment]
Currently bundled version achieves its goal well and seems to be the most stable. I'm waiting until 0.7 hit the main branch to move forward with any potential fixes that might be required.

For now you can upgrade Optiscaler yourself by replacing ``$HOME/fgmod/dlss-enabler-upscaler.dll`` with a newer version but it's not an intended change and you might see issues. First thing I would watch out for is ``UseFGSwapChain`` which might need to be set to false, disabling Opti's FG.
