### ISSUE TITLE
Red Dead Redemption freezes on Startup with fgmod enabled

### ISSUE THREAD

**Issue by andriuspetravicius** [FakeMichau/fgmod#8]
RDR1 launches for the first time with this mod enabled and works great with Frame Gen and all, but if you exit and launch it again it freezes on startup/loading screens.

**Comment by FakeMichau** [comment]
I've noticed that myself and is on my radar already. Could you confirm that the issue goes away by setting ``force_reflex = 1`` inside fakenvapi.ini? 
fgmod doesn't override the config files so you will need to change this value inside the game folder's fakenvapi.ini

**Comment by andriuspetravicius** [comment]
That fixed the issue, thank you!

**Comment by FakeMichau** [comment]
Should be fixed with https://github.com/FakeMichau/fakenvapi/commit/d8eed45438f5606a13a94e8979b99ac07c5966de which is used by fgmod.
